"""categories_events_users_full

Revision ID: 279d6a05a53d
Revises: c7b8d9e0f1a2
Create Date: 2026-06-03 01:12:59.816225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279d6a05a53d'
down_revision = 'c7b8d9e0f1a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_category_is_active', 'categories', ['is_active'], unique=False)
    op.create_index('ix_category_name', 'categories', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_ar', sa.String(), nullable=True),
    sa.Column('title_fr', sa.String(), nullable=True),
    sa.Column('title_tam', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_tam', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('commune', sa.String(), nullable=False),
    sa.Column('wilaya', sa.String(), nullable=False),
    sa.Column('date_begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('remaining_spots', sa.Integer(), nullable=True),
    sa.Column('registration_link', sa.String(), nullable=True),
    sa.Column('registration_contact', sa.String(), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=True),
    sa.Column('is_volunteering', sa.Boolean(), nullable=True),
    sa.Column('volunteer_skills', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_category_id', 'events', ['category_id'], unique=False)
    op.create_index('ix_event_date_begin', 'events', ['date_begin'], unique=False)
    op.create_index('ix_event_is_active', 'events', ['is_active'], unique=False)
    op.create_index('ix_event_postal_code', 'events', ['postal_code'], unique=False)
    op.create_index('ix_event_status', 'events', ['status'], unique=False)
    op.create_table('user_favourite_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('user_registered_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.drop_index('ix_program_category', table_name='programs')
    op.drop_index('ix_program_center_id', table_name='programs')
    op.drop_index('ix_program_is_active', table_name='programs')
    op.drop_index('ix_program_language', table_name='programs')
    op.drop_index('ix_querylog_cache_hit', table_name='query_logs')
    op.drop_index('ix_querylog_created_at', table_name='query_logs')
    op.drop_index('ix_youthcenter_is_active', table_name='youth_centers')
    op.drop_index('ix_youthcenter_wilaya', table_name='youth_centers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_youthcenter_wilaya', 'youth_centers', ['wilaya'], unique=False)
    op.create_index('ix_youthcenter_is_active', 'youth_centers', ['is_active'], unique=False)
    op.create_index('ix_querylog_created_at', 'query_logs', ['created_at'], unique=False)
    op.create_index('ix_querylog_cache_hit', 'query_logs', ['cache_hit'], unique=False)
    op.create_index('ix_program_language', 'programs', ['language'], unique=False)
    op.create_index('ix_program_is_active', 'programs', ['is_active'], unique=False)
    op.create_index('ix_program_center_id', 'programs', ['center_id'], unique=False)
    op.create_index('ix_program_category', 'programs', ['category'], unique=False)
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('user_registered_events')
    op.drop_table('user_favourite_categories')
    op.drop_index('ix_event_status', table_name='events')
    op.drop_index('ix_event_postal_code', table_name='events')
    op.drop_index('ix_event_is_active', table_name='events')
    op.drop_index('ix_event_date_begin', table_name='events')
    op.drop_index('ix_event_category_id', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_index('ix_user_is_active', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_category_name', table_name='categories')
    op.drop_index('ix_category_is_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
