import { Event, YouthCenter, Comment, Notification, User } from '@/types';

export const WILAYAS = [
  { code: '01', name: 'Adrar', nameAr: 'أدرار', nameFr: 'Adrar', lat: 27.87, lng: -0.29 },
  { code: '02', name: 'Chlef', nameAr: 'الشلف', nameFr: 'Chlef', lat: 36.16, lng: 1.33 },
  { code: '03', name: 'Laghouat', nameAr: 'الأغواط', nameFr: 'Laghouat', lat: 33.8, lng: 2.87 },
  { code: '04', name: 'Oum El Bouaghi', nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi', lat: 35.87, lng: 7.11 },
  { code: '05', name: 'Batna', nameAr: 'باتنة', nameFr: 'Batna', lat: 35.55, lng: 6.17 },
  { code: '06', name: 'Béjaïa', nameAr: 'بجاية', nameFr: 'Béjaïa', lat: 36.75, lng: 5.08 },
  { code: '07', name: 'Biskra', nameAr: 'بسكرة', nameFr: 'Biskra', lat: 34.85, lng: 5.73 },
  { code: '08', name: 'Béchar', nameAr: 'بشار', nameFr: 'Béchar', lat: 31.62, lng: -2.22 },
  { code: '09', name: 'Blida', nameAr: 'البليدة', nameFr: 'Blida', lat: 36.47, lng: 2.83 },
  { code: '10', name: 'Bouira', nameAr: 'البويرة', nameFr: 'Bouira', lat: 36.38, lng: 3.9 },
  { code: '11', name: 'Tamanrasset', nameAr: 'تمنراست', nameFr: 'Tamanrasset', lat: 22.78, lng: 5.52 },
  { code: '12', name: 'Tébessa', nameAr: 'تبسة', nameFr: 'Tébessa', lat: 35.4, lng: 8.12 },
  { code: '13', name: 'Tlemcen', nameAr: 'تلمسان', nameFr: 'Tlemcen', lat: 34.88, lng: -1.31 },
  { code: '14', name: 'Tiaret', nameAr: 'تيارت', nameFr: 'Tiaret', lat: 35.37, lng: 1.32 },
  { code: '15', name: 'Tizi Ouzou', nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou', lat: 36.71, lng: 4.05 },
  { code: '16', name: 'Alger', nameAr: 'الجزائر', nameFr: 'Alger', lat: 36.75, lng: 3.06 },
  { code: '17', name: 'Djelfa', nameAr: 'الجلفة', nameFr: 'Djelfa', lat: 34.67, lng: 3.25 },
  { code: '18', name: 'Jijel', nameAr: 'جيجل', nameFr: 'Jijel', lat: 36.82, lng: 5.76 },
  { code: '19', name: 'Sétif', nameAr: 'سطيف', nameFr: 'Sétif', lat: 36.19, lng: 5.41 },
  { code: '20', name: 'Saïda', nameAr: 'سعيدة', nameFr: 'Saïda', lat: 34.83, lng: 0.15 },
  { code: '21', name: 'Skikda', nameAr: 'سكيكدة', nameFr: 'Skikda', lat: 36.87, lng: 6.9 },
  { code: '22', name: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbès', lat: 35.2, lng: -0.63 },
  { code: '23', name: 'Annaba', nameAr: 'عنابة', nameFr: 'Annaba', lat: 36.9, lng: 7.77 },
  { code: '24', name: 'Guelma', nameAr: 'قالمة', nameFr: 'Guelma', lat: 36.46, lng: 7.42 },
  { code: '25', name: 'Constantine', nameAr: 'قسنطينة', nameFr: 'Constantine', lat: 36.37, lng: 6.61 },
  { code: '26', name: 'Médéa', nameAr: 'المدية', nameFr: 'Médéa', lat: 36.26, lng: 2.75 },
  { code: '27', name: 'Mostaganem', nameAr: 'مستغانم', nameFr: 'Mostaganem', lat: 35.93, lng: 0.09 },
  { code: '28', name: 'M\'Sila', nameAr: 'المسيلة', nameFr: 'M\'Sila', lat: 35.7, lng: 4.54 },
  { code: '29', name: 'Mascara', nameAr: 'معسكر', nameFr: 'Mascara', lat: 35.4, lng: 0.14 },
  { code: '30', name: 'Ouargla', nameAr: 'ورقلة', nameFr: 'Ouargla', lat: 31.95, lng: 5.32 },
  { code: '31', name: 'Oran', nameAr: 'وهران', nameFr: 'Oran', lat: 35.69, lng: -0.64 },
  { code: '32', name: 'El Bayadh', nameAr: 'البيض', nameFr: 'El Bayadh', lat: 33.68, lng: 1.02 },
  { code: '33', name: 'Illizi', nameAr: 'إيليزي', nameFr: 'Illizi', lat: 26.48, lng: 8.46 },
  { code: '34', name: 'Bordj Bou Arreridj', nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arreridj', lat: 36.07, lng: 4.76 },
  { code: '35', name: 'Boumerdès', nameAr: 'بومرداس', nameFr: 'Boumerdès', lat: 36.76, lng: 3.47 },
  { code: '36', name: 'El Tarf', nameAr: 'الطارف', nameFr: 'El Tarf', lat: 36.76, lng: 8.31 },
  { code: '37', name: 'Tindouf', nameAr: 'تندوف', nameFr: 'Tindouf', lat: 27.67, lng: -8.14 },
  { code: '38', name: 'Tissemsilt', nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt', lat: 35.6, lng: 1.81 },
  { code: '39', name: 'El Oued', nameAr: 'الوادي', nameFr: 'El Oued', lat: 33.36, lng: 6.86 },
  { code: '40', name: 'Khenchela', nameAr: 'خنشلة', nameFr: 'Khenchela', lat: 35.43, lng: 7.14 },
  { code: '41', name: 'Souk Ahras', nameAr: 'سوق أهراس', nameFr: 'Souk Ahras', lat: 36.28, lng: 7.95 },
  { code: '42', name: 'Tipaza', nameAr: 'تيبازة', nameFr: 'Tipaza', lat: 36.59, lng: 2.45 },
  { code: '43', name: 'Mila', nameAr: 'ميلة', nameFr: 'Mila', lat: 36.45, lng: 6.26 },
  { code: '44', name: 'Aïn Defla', nameAr: 'عين الدفلى', nameFr: 'Aïn Defla', lat: 36.26, lng: 1.96 },
  { code: '45', name: 'Naâma', nameAr: 'النعامة', nameFr: 'Naâma', lat: 33.26, lng: -0.31 },
  { code: '46', name: 'Aïn Témouchent', nameAr: 'عين تموشنت', nameFr: 'Aïn Témouchent', lat: 35.3, lng: -1.14 },
  { code: '47', name: 'Ghardaïa', nameAr: 'غرداية', nameFr: 'Ghardaïa', lat: 32.48, lng: 3.67 },
  { code: '48', name: 'Relizane', nameAr: 'غليزان', nameFr: 'Relizane', lat: 35.73, lng: 0.55 },
  { code: '49', name: 'Timimoun', nameAr: 'تيميمون', nameFr: 'Timimoun', lat: 29.26, lng: 0.23 },
  { code: '50', name: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar', lat: 21.32, lng: 0.95 },
  { code: '51', name: 'Ouled Djellal', nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal', lat: 34.42, lng: 5.06 },
  { code: '52', name: 'Béni Abbès', nameAr: 'بني عباس', nameFr: 'Béni Abbès', lat: 30.13, lng: -2.17 },
  { code: '53', name: 'In Salah', nameAr: 'عين صالح', nameFr: 'In Salah', lat: 27.19, lng: 2.48 },
  { code: '54', name: 'In Guezzam', nameAr: 'عين قزام', nameFr: 'In Guezzam', lat: 19.57, lng: 5.77 },
  { code: '55', name: 'Touggourt', nameAr: 'تقرت', nameFr: 'Touggourt', lat: 33.1, lng: 6.06 },
  { code: '56', name: 'Djanet', nameAr: 'جانت', nameFr: 'Djanet', lat: 24.55, lng: 9.48 },
  { code: '57', name: 'El M\'Ghair', nameAr: 'المغير', nameFr: 'El M\'Ghair', lat: 33.95, lng: 5.92 },
  { code: '58', name: 'El Meniaa', nameAr: 'المنيعة', nameFr: 'El Meniaa', lat: 30.58, lng: 2.88 },
];

export const INTEREST_ICONS: Record<string, string> = {
  technology: '💻', programming: '🖥️', entrepreneurship: '🚀',
  sports: '⚽', football: '🏟️', art: '🎨', music: '🎵',
  photography: '📸', environment: '🌱', volunteering: '🤝',
  languages: '🌍', ai: '🤖', robotics: '🔧', gaming: '🎮',
  culture: '🏛️', science: '🔬', education: '📚', health: '❤️',
  workshop: '🛠️', competition: '🏆', training: '📋',
};

export const mockCenters: YouthCenter[] = [
  { id: 'c1', name: 'Youth Center Algiers Central', nameAr: 'دار الشباب الجزائر وسط', nameFr: 'Maison de Jeunes Alger Centre', wilaya: 'Alger', city: 'Alger Centre', address: 'Rue Didouche Mourad, Alger', lat: 36.7538, lng: 3.0588, phone: '021-123456', capacity: 200, facilities: ['WiFi', 'Salle de sport', 'Bibliothèque', 'Salle informatique'], rating: 4.5, reviewCount: 128 },
  { id: 'c2', name: 'Oran Youth Hub', nameAr: 'مركز شباب وهران', nameFr: 'Centre de Jeunesse Oran', wilaya: 'Oran', city: 'Oran', address: 'Boulevard de l\'ANP, Oran', lat: 35.6971, lng: -0.6308, phone: '041-654321', capacity: 150, facilities: ['WiFi', 'Théâtre', 'Salle de musique'], rating: 4.2, reviewCount: 89 },
  { id: 'c3', name: 'Constantine Youth Palace', nameAr: 'قصر الشباب قسنطينة', nameFr: 'Palais de la Jeunesse Constantine', wilaya: 'Constantine', city: 'Constantine', address: 'Avenue Aouati Mostefa', lat: 36.365, lng: 6.6147, phone: '031-789012', capacity: 300, facilities: ['WiFi', 'Piscine', 'Salle de conférence', 'Studio'], rating: 4.7, reviewCount: 215 },
  { id: 'c4', name: 'Sétif Innovation Center', nameAr: 'مركز الابتكار سطيف', nameFr: 'Centre d\'Innovation Sétif', wilaya: 'Sétif', city: 'Sétif', address: 'Cité 1000 logements', lat: 36.191, lng: 5.4117, capacity: 120, facilities: ['WiFi', 'FabLab', 'Coworking'], rating: 4.4, reviewCount: 67 },
  { id: 'c5', name: 'Béjaïa Youth Space', nameAr: 'فضاء الشباب بجاية', nameFr: 'Espace Jeunesse Béjaïa', wilaya: 'Béjaïa', city: 'Béjaïa', address: 'Quartier Seghir', lat: 36.7509, lng: 5.0567, capacity: 100, facilities: ['WiFi', 'Bibliothèque', 'Salle polyvalente'], rating: 4.1, reviewCount: 45 },
  { id: 'c6', name: 'Tizi Ouzou Community Center', nameAr: 'المركز المجتمعي تيزي وزو', nameFr: 'Centre Communautaire Tizi Ouzou', wilaya: 'Tizi Ouzou', city: 'Tizi Ouzou', address: 'Avenue Abane Ramdane', lat: 36.7169, lng: 4.0497, capacity: 180, facilities: ['WiFi', 'Atelier artisanat', 'Salle de sport'], rating: 4.3, reviewCount: 93 },
  { id: 'c7', name: 'Annaba Digital Hub', nameAr: 'المركز الرقمي عنابة', nameFr: 'Hub Numérique Annaba', wilaya: 'Annaba', city: 'Annaba', address: 'Cours de la Révolution', lat: 36.9, lng: 7.7667, capacity: 80, facilities: ['WiFi', 'Salle informatique', 'Studio vidéo'], rating: 4.6, reviewCount: 72 },
  { id: 'c8', name: 'Blida Green Youth Center', nameAr: 'مركز الشباب الأخضر البليدة', nameFr: 'Centre de Jeunesse Vert Blida', wilaya: 'Blida', city: 'Blida', address: 'Rue des Roses', lat: 36.4722, lng: 2.8278, capacity: 130, facilities: ['WiFi', 'Jardin', 'Salle de conférence'], rating: 4.0, reviewCount: 38 },
];

export const mockEvents: Event[] = [
  {
    id: 'e1', title: 'AI & Machine Learning Workshop', titleAr: 'ورشة الذكاء الاصطناعي والتعلم الآلي', titleFr: 'Atelier IA & Machine Learning',
    description: 'Hands-on workshop covering the fundamentals of AI and machine learning. Learn to build your first ML model using Python and TensorFlow. Perfect for beginners and intermediate developers.',
    descriptionAr: 'ورشة عملية تغطي أساسيات الذكاء الاصطناعي والتعلم الآلي', descriptionFr: 'Atelier pratique couvrant les fondamentaux de l\'IA et du machine learning',
    category: 'ai', tags: ['ai', 'programming', 'technology'], status: 'upcoming',
    startDate: '2026-06-15T09:00:00', endDate: '2026-06-15T17:00:00',
    location: 'Youth Center Algiers Central', wilaya: 'Alger', city: 'Alger Centre',
    lat: 36.7538, lng: 3.0588, centerId: 'c1', centerName: 'Youth Center Algiers Central',
    organizerName: 'ODEJ Alger', image: '/images/ai-workshop.png',
    capacity: 50, registered: 38, isFree: true, ageRange: { min: 16, max: 30 },
    requirements: ['Laptop', 'Python basics'], contactEmail: 'ai@odej.dz'
  },
  {
    id: 'e2', title: 'Startup Weekend Algeria', titleAr: 'عطلة نهاية الأسبوع للشركات الناشئة', titleFr: 'Startup Weekend Algérie',
    description: 'Join the biggest entrepreneurship event in Algeria! 54 hours to pitch, build, and launch your startup idea. Mentors, investors, and prizes await.',
    descriptionAr: 'انضم إلى أكبر حدث ريادي في الجزائر', descriptionFr: 'Rejoignez le plus grand événement d\'entrepreneuriat en Algérie',
    category: 'entrepreneurship', tags: ['entrepreneurship', 'technology', 'training'], status: 'upcoming',
    startDate: '2026-06-20T18:00:00', endDate: '2026-06-22T20:00:00',
    location: 'Oran Youth Hub', wilaya: 'Oran', city: 'Oran',
    lat: 35.6971, lng: -0.6308, centerId: 'c2', centerName: 'Oran Youth Hub',
    organizerName: 'ODEJ Oran', image: '/images/startup-weekend.png',
    capacity: 100, registered: 87, isFree: false, price: 500, ageRange: { min: 18, max: 35 },
    contactEmail: 'startup@odej.dz'
  },
  {
    id: 'e3', title: 'Photography Contest: Algeria Through Your Lens', titleAr: 'مسابقة التصوير: الجزائر من عدستك', titleFr: 'Concours Photo: L\'Algérie à travers votre objectif',
    description: 'Capture the beauty of Algeria. Submit your best photographs showcasing Algerian landscapes, culture, and daily life. Amazing prizes for the top 3 winners!',
    descriptionAr: 'التقط جمال الجزائر وشارك أفضل صورك', descriptionFr: 'Capturez la beauté de l\'Algérie',
    category: 'photography', tags: ['photography', 'art', 'culture', 'competition'], status: 'upcoming',
    startDate: '2026-06-10T00:00:00', endDate: '2026-07-10T23:59:00',
    location: 'Online + Constantine Youth Palace', wilaya: 'Constantine', city: 'Constantine',
    lat: 36.365, lng: 6.6147, centerId: 'c3', centerName: 'Constantine Youth Palace',
    organizerName: 'ODEJ Constantine', image: '/images/photography-contest.png',
    capacity: 500, registered: 234, isFree: true, ageRange: { min: 15, max: 35 },
    contactEmail: 'photo@odej.dz'
  },
  {
    id: 'e4', title: 'Green Hackathon: Eco Solutions', titleAr: 'هاكاثون أخضر: حلول بيئية', titleFr: 'Hackathon Vert: Solutions Écologiques',
    description: 'Build innovative tech solutions for environmental challenges in Algeria. 48 hours of coding, creativity, and collaboration for a greener future.',
    descriptionAr: 'ابتكر حلول تقنية للتحديات البيئية', descriptionFr: 'Créez des solutions tech innovantes pour les défis environnementaux',
    category: 'environment', tags: ['environment', 'programming', 'technology', 'competition'], status: 'upcoming',
    startDate: '2026-07-01T08:00:00', endDate: '2026-07-03T18:00:00',
    location: 'Sétif Innovation Center', wilaya: 'Sétif', city: 'Sétif',
    lat: 36.191, lng: 5.4117, centerId: 'c4', centerName: 'Sétif Innovation Center',
    organizerName: 'ODEJ Sétif', image: '/images/green-hackathon.png',
    capacity: 80, registered: 45, isFree: true, ageRange: { min: 17, max: 30 },
    requirements: ['Laptop', 'Team of 3-5'], contactEmail: 'green@odej.dz'
  },
  {
    id: 'e5', title: 'Football Tournament U25', titleAr: 'دوري كرة القدم تحت 25', titleFr: 'Tournoi de Football U25',
    description: 'Inter-wilaya football tournament for youth under 25. Register your team and compete for the championship title!',
    descriptionAr: 'دوري كرة قدم بين الولايات للشباب تحت 25 سنة', descriptionFr: 'Tournoi de football inter-wilayas pour les jeunes de moins de 25 ans',
    category: 'football', tags: ['football', 'sports', 'competition'], status: 'ongoing',
    startDate: '2026-06-01T14:00:00', endDate: '2026-06-30T18:00:00',
    location: 'Béjaïa Youth Space', wilaya: 'Béjaïa', city: 'Béjaïa',
    lat: 36.7509, lng: 5.0567, centerId: 'c5', centerName: 'Béjaïa Youth Space',
    organizerName: 'ODEJ Béjaïa', image: '/images/football-tournament.png',
    capacity: 160, registered: 144, isFree: true, ageRange: { min: 16, max: 25 },
    requirements: ['Team of 11 players', 'Medical certificate'], contactEmail: 'sports@odej.dz'
  },
  {
    id: 'e6', title: 'Amazigh Culture Festival', titleAr: 'مهرجان الثقافة الأمازيغية', titleFr: 'Festival de la Culture Amazighe',
    description: 'Celebrate Amazigh heritage with music, dance, art exhibitions, and traditional crafts. Open to all ages!',
    descriptionAr: 'احتفل بالتراث الأمازيغي مع الموسيقى والرقص والفنون', descriptionFr: 'Célébrez l\'héritage amazigh avec musique, danse et artisanat',
    category: 'culture', tags: ['culture', 'music', 'art'], status: 'upcoming',
    startDate: '2026-06-25T10:00:00', endDate: '2026-06-27T22:00:00',
    location: 'Tizi Ouzou Community Center', wilaya: 'Tizi Ouzou', city: 'Tizi Ouzou',
    lat: 36.7169, lng: 4.0497, centerId: 'c6', centerName: 'Tizi Ouzou Community Center',
    organizerName: 'ODEJ Tizi Ouzou', image: '/images/amazigh-festival.png',
    capacity: 1000, registered: 456, isFree: true, ageRange: { min: 0, max: 99 },
    contactEmail: 'culture@odej.dz'
  },
  {
    id: 'e7', title: 'Robotics Workshop for Beginners', titleAr: 'ورشة الروبوتيك للمبتدئين', titleFr: 'Atelier Robotique pour Débutants',
    description: 'Learn the basics of robotics with Arduino. Build your own robot in this 2-day intensive workshop. All materials provided!',
    descriptionAr: 'تعلم أساسيات الروبوتيك مع أردوينو', descriptionFr: 'Apprenez les bases de la robotique avec Arduino',
    category: 'robotics', tags: ['robotics', 'technology', 'education', 'workshop'], status: 'upcoming',
    startDate: '2026-07-05T09:00:00', endDate: '2026-07-06T17:00:00',
    location: 'Annaba Digital Hub', wilaya: 'Annaba', city: 'Annaba',
    lat: 36.9, lng: 7.7667, centerId: 'c7', centerName: 'Annaba Digital Hub',
    organizerName: 'ODEJ Annaba', image: '/images/robotics.jpg',
    capacity: 30, registered: 22, isFree: true, ageRange: { min: 14, max: 25 },
    requirements: ['No prior experience needed'], contactEmail: 'robotics@odej.dz'
  },
  {
    id: 'e8', title: 'Volunteer for Clean Blida Campaign', titleAr: 'تطوع لحملة البليدة نظيفة', titleFr: 'Volontariat pour Blida Propre',
    description: 'Join hundreds of volunteers in cleaning Blida\'s parks and public spaces. Make a real difference in your community!',
    descriptionAr: 'انضم إلى مئات المتطوعين في تنظيف حدائق البليدة', descriptionFr: 'Rejoignez des centaines de bénévoles pour nettoyer les parcs de Blida',
    category: 'volunteering', tags: ['volunteering', 'environment'], status: 'upcoming',
    startDate: '2026-06-14T07:00:00', endDate: '2026-06-14T13:00:00',
    location: 'Blida Green Youth Center', wilaya: 'Blida', city: 'Blida',
    lat: 36.4722, lng: 2.8278, centerId: 'c8', centerName: 'Blida Green Youth Center',
    organizerName: 'ODEJ Blida', image: '/images/volunteering.jpg',
    capacity: 300, registered: 178, isFree: true, ageRange: { min: 14, max: 60 },
    contactEmail: 'volunteer@odej.dz'
  },
  {
    id: 'e9', title: 'Music Production Masterclass', titleAr: 'دورة إنتاج الموسيقى', titleFr: 'Masterclass Production Musicale',
    description: 'Learn professional music production techniques with industry experts. From beat-making to mixing and mastering.',
    descriptionAr: 'تعلم تقنيات الإنتاج الموسيقي الاحترافية', descriptionFr: 'Apprenez les techniques de production musicale professionnelle',
    category: 'music', tags: ['music', 'art', 'training'], status: 'upcoming',
    startDate: '2026-07-10T14:00:00', endDate: '2026-07-12T18:00:00',
    location: 'Oran Youth Hub', wilaya: 'Oran', city: 'Oran',
    lat: 35.6971, lng: -0.6308, centerId: 'c2', centerName: 'Oran Youth Hub',
    organizerName: 'ODEJ Oran', image: '/images/music.jpg',
    capacity: 25, registered: 19, isFree: false, price: 1000, ageRange: { min: 16, max: 30 },
    contactEmail: 'music@odej.dz'
  },
  {
    id: 'e10', title: 'Science Fair 2026', titleAr: 'معرض العلوم 2026', titleFr: 'Foire aux Sciences 2026',
    description: 'Present your scientific projects and compete for national recognition. Open to all STEM students.',
    descriptionAr: 'قدم مشاريعك العلمية وتنافس على المستوى الوطني', descriptionFr: 'Présentez vos projets scientifiques et concourez au niveau national',
    category: 'science', tags: ['science', 'education', 'competition'], status: 'upcoming',
    startDate: '2026-07-15T08:00:00', endDate: '2026-07-17T18:00:00',
    location: 'Youth Center Algiers Central', wilaya: 'Alger', city: 'Alger Centre',
    lat: 36.7538, lng: 3.0588, centerId: 'c1', centerName: 'Youth Center Algiers Central',
    organizerName: 'ODEJ Alger', image: '/images/science-fair.jpg',
    capacity: 200, registered: 95, isFree: true, ageRange: { min: 15, max: 28 },
    contactEmail: 'science@odej.dz'
  },
  {
    id: 'e11', title: 'Gaming Tournament: Esports League', titleAr: 'بطولة الألعاب: الدوري الإلكتروني', titleFr: 'Tournoi Gaming: Ligue Esports',
    description: 'Compete in the biggest esports tournament. Games include Valorant, League of Legends, and FIFA. Solo and team registrations.',
    descriptionAr: 'شارك في أكبر بطولة رياضات إلكترونية', descriptionFr: 'Participez au plus grand tournoi esport',
    category: 'gaming', tags: ['gaming', 'competition', 'technology'], status: 'upcoming',
    startDate: '2026-07-20T10:00:00', endDate: '2026-07-22T22:00:00',
    location: 'Constantine Youth Palace', wilaya: 'Constantine', city: 'Constantine',
    lat: 36.365, lng: 6.6147, centerId: 'c3', centerName: 'Constantine Youth Palace',
    organizerName: 'ODEJ Constantine', image: '/images/gaming.jpg',
    capacity: 200, registered: 156, isFree: false, price: 200, ageRange: { min: 16, max: 28 },
    contactEmail: 'gaming@odej.dz'
  },
  {
    id: 'e12', title: 'English Language Bootcamp', titleAr: 'معسكر اللغة الإنجليزية', titleFr: 'Bootcamp Langue Anglaise',
    description: 'Intensive 2-week English language program. From beginner to conversational. Native speakers and certified teachers.',
    descriptionAr: 'برنامج مكثف للغة الإنجليزية لمدة أسبوعين', descriptionFr: 'Programme intensif de langue anglaise de 2 semaines',
    category: 'languages', tags: ['languages', 'education', 'training'], status: 'upcoming',
    startDate: '2026-07-07T09:00:00', endDate: '2026-07-21T16:00:00',
    location: 'Sétif Innovation Center', wilaya: 'Sétif', city: 'Sétif',
    lat: 36.191, lng: 5.4117, centerId: 'c4', centerName: 'Sétif Innovation Center',
    organizerName: 'ODEJ Sétif', image: '/images/languages.jpg',
    capacity: 40, registered: 35, isFree: true, ageRange: { min: 16, max: 30 },
    contactEmail: 'languages@odej.dz'
  },
];

export const mockComments: Comment[] = [
  { id: 'cm1', userId: 'u2', userName: 'Amina B.', eventId: 'e1', content: 'Super excité pour cet atelier! J\'ai hâte d\'apprendre le ML!', createdAt: '2026-06-05T10:30:00', likes: 12 },
  { id: 'cm2', userId: 'u3', userName: 'Karim M.', eventId: 'e1', content: 'Est-ce qu\'on a besoin d\'expérience préalable en Python?', createdAt: '2026-06-05T14:20:00', likes: 5 },
  { id: 'cm3', userId: 'u4', userName: 'Lina T.', eventId: 'e2', content: 'L\'année dernière c\'était incroyable. Je recommande à tout le monde!', createdAt: '2026-06-06T09:00:00', likes: 23 },
  { id: 'cm4', userId: 'u5', userName: 'Yacine D.', eventId: 'e3', content: 'J\'ai déjà pris quelques photos magnifiques pour ce concours 📸', createdAt: '2026-06-07T16:45:00', likes: 18 },
  { id: 'cm5', userId: 'u6', userName: 'Sara K.', eventId: 'e4', content: 'Notre équipe est prête! On va construire une app de recyclage.', createdAt: '2026-06-08T11:15:00', likes: 8 },
];

export const mockNotifications: Notification[] = [
  { id: 'n1', type: 'event', title: 'Nouvel événement', message: 'AI & Machine Learning Workshop à Alger - Inscrivez-vous!', eventId: 'e1', read: false, createdAt: '2026-06-05T08:00:00' },
  { id: 'n2', type: 'deadline', title: 'Rappel', message: 'Il reste 3 jours pour s\'inscrire au Startup Weekend', eventId: 'e2', read: false, createdAt: '2026-06-17T09:00:00' },
  { id: 'n3', type: 'opportunity', title: 'Nouvelle opportunité', message: 'Volunteer for Clean Blida - Rejoignez la campagne!', eventId: 'e8', read: true, createdAt: '2026-06-10T07:00:00' },
  { id: 'n4', type: 'event', title: 'Événement populaire', message: 'Gaming Tournament a dépassé 150 inscriptions!', eventId: 'e11', read: true, createdAt: '2026-06-12T15:00:00' },
  { id: 'n5', type: 'system', title: 'Bienvenue!', message: 'Bienvenue sur It\'s where! Personnalisez votre profil.', read: true, createdAt: '2026-06-01T00:00:00' },
];

export const mockUser: User = {
  id: 'u1', name: 'Zaki Hachemi', email: 'zaki@itswhere.dz',
  role: 'youth', wilaya: 'Sétif', city: 'El Eulma',
  interests: ['programming', 'ai', 'technology', 'entrepreneurship', 'gaming'],
  savedEvents: ['e1', 'e4'], joinedEvents: ['e1', 'e3'],
  createdAt: '2026-06-01T00:00:00', lang: 'fr',
};
